---
title: "中文简历"
editor: 
  markdown: 
    wrap: 72
---

<!-- page-local styles: only affect this page -->
<style>
/* increase gap below the page title and above the first section */
h1 {
  margin-bottom: 3rem !important;
}
h1 + h2 {
  margin-top: 1.25rem !important;
}
</style>


## 个人简介

邝琪，应用经济学家与数据科学家，研究领域涵盖教育政策、发展经济学与应用计量经济学，重点关注不平等、社会流动性以及对气候冲击和制度冲击的韧性。她结合使用行政数据、住户调查数据与地理空间信息，研究公共政策与外部冲击对个体与制度结果的影响。

现任职于经济合作与发展组织（OECD）教育与技能司，担任数据科学家，参与《教育概览》（Education at a Glance）及 UOE（联合国教科文组织–OECD–欧盟统计局）数据项目，主要从事数据采集、清洗、核验与指标构建等高强度数据分析工作。她使用 R 与 Stata 开发和维护分析工具，以确保数据与指标计算的质量、国际可比性与稳健性，并牵头将指标生产流程从 Stata do-file 迁移至基于 R 的工作流，开发内部 R 软件包以保障方法一致性。其研究重点包括教师议题及学校与机构层级的细分数据分析，并负责多个基于大规模行政数据与地理空间分析的学校数据项目。

她毕业于巴黎经济学院（Paris School of Economics），获经济学硕士学位（Analysis and Policy in Economics 项目），并以优异成绩完成学业, 并获法国政府硕士奖学金资助。其硕士论文《气候变率冲击下的韧性》利用卫星数据、空间分析与计量方法研究孟加拉国家庭在气候冲击下的决策行为。
其研究经历涵盖气候与发展经济学、政治经济学以及城市与区域经济学，参与过多项研究项目，包括：基于机器学习与大规模文本数据的印度环境监管研究、中国财政转移支付与人口集聚研究，以及基于原创田野调查的搬迁人口社会融合研究。她熟练掌握 Stata、R、Python 及 QGIS、ArcGIS 等 GIS 工具，并具备问卷设计与田野调查研究经验。

- 邮箱：kuangqi1024@gmail.com (优先); qi.kuang@oecd.org
- 领英：[Qi KUANG](https://www.linkedin.com/in/qi-kuang-a545b2234/)
- Github: <https://github.com/QiKuang1999>

## 教育和工作背景

- 2023 至今: 经济与合作发展组织（OECD）数据分析师
- 2021 - 2024: 巴黎经济学院 Analysis and Policy in Economics（经济学硕士）
- 2017 - 2021: 浙江大学 经济学院 本科（经济学学士）

## 研究兴趣

- 不平等，发展经济学
- 应用经济学
- 教育经济学

## 公开发表
- 黄祖辉，吴沁霞，邝琪. 易地扶贫移民的社会融合——基于贵州黄平县的实证分析, 贵州大学学报, 2021(3):46-57 [(Link)](http://je.gzu.edu.cn/gzdxskb/gzdxskb/article/abstract/1000-5099-2021-03-0046-12).
- 经济与合作发展组织(OECD).教育概览(Education at a Glance 2024), 2024: [Chapter D2](https://www.oecd.org/en/publications/education-at-a-glance-2024_c00cad36-en/full-report/what-is-the-student-teacher-ratio-and-how-large-are-classes-and-schools_bb95b097.html#chapter-d1e25672-30c964da4a).
- 经济与合作发展组织(OECD).教育概览(Education at a Glance 2025), 2025: [Chapter D2](https://www.oecd.org/en/publications/education-at-a-glance-2025_1c0d9c79-en/full-report/how-do-student-teacher-ratios-and-class-sizes-vary-across-education-levels-up-to-upper-secondary-education_76b87b21.html#chapter-d1e29099-39d77bedc1), [Chapter D5](https://www.oecd.org/en/publications/education-at-a-glance-2025_1c0d9c79-en/full-report/how-do-academic-staff-profiles-and-institutional-characteristics-shape-tertiary-education_4128fd24.html#chapter-d1e34107-2a30691466), [Box4.4](https://www.oecd.org/en/publications/education-at-a-glance-2025_1c0d9c79-en/full-report/how-do-student-profiles-study-choices-and-mobility-trends-shape-tertiary-education_97e1e2bd.html#title-416f496abe).

